//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// paint_res.rc

#define ID_OPEN                             100
#define ID_SAVE                             101
#define ID_EXIT                             102
#define ID_CUT                              103
#define ID_COPY                             104
#define ID_PASTE                            105
#define ID_DELETE                           106
#define ID_SELECT_ALL                       107
#define ID_SELECT                           108
#define ID_PENCIL                           109

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     110
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
